name: CML with Python 
on: [push]

defaults:
  run:
    working-directory: CML

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Model Flow
          pip install -r requirements.txt
          python train_model.py
          
          echo "## RF Model metrics\n" >> model_report.md
          cat rf_metrics.txt >> model_report.md
          
          echo "## Feature Importance" >> model_report.md
          cml-publish rf_feature_importance.png --md >> model_report.md
          
          cml-send-comment model_report.md
